# Uncomment the next line to define a global platform for your project
# platform :ios, '14.4'

target 'Cars' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Cars

  pod 'RevealingSplashView'
  pod 'TweeTextField'
  
  pod 'Firebase'
  
  pod 'Firebase/Auth'
  
  pod 'Firebase/Firestore'
  
  pod 'Firebase/Storage'
  
  pod 'Firebase/Analytics'
    
  pod 'Firebase/Crashlytics'
  
  pod 'GoogleSignIn'
  
  
  pod 'SDWebImage', '~> 5.0'
 
  pod 'SVProgressHUD'
  pod 'lottie-ios'
  
  pod 'ImagePicker'
  
  pod 'Lightbox'
  
  pod 'Gallery'

  pod 'RealmSwift'

  target 'CarsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CarsUITests' do
    # Pods for testing
  end

end
