# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ARABAMI SAT' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ARABAMI SAT

  pod 'Firebase'
  
  pod 'Firebase/Auth'
  
  pod 'Firebase/Firestore'
  
  pod 'Firebase/Storage'
  
  pod 'Firebase/Analytics'
  

  
  pod 'Firebase/Messaging'
  
  pod 'Firebase/Crashlytics'
  
  pod 'SDWebImage', '~> 5.0'
  pod  'GoogleSignIn'

  
  pod "JDropDownAlert"
  
  pod 'SVProgressHUD'
  
  pod 'PopupDialog', '~> 1.1'
  
  pod 'SwiftyAttributes'
  
  pod 'ActiveLabel'

  
  pod 'lottie-ios'
  
  pod 'ImagePicker'
  
  pod 'Lightbox'
  
  pod 'Gallery'
  


  pod 'SwipeCellKit'
  target 'ARABAMI SATTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ARABAMI SATUITests' do
    # Pods for testing
  end

end
